version: "3.7"
services:
  ia-upload:
    build:
      context: .
    user: "${IAUPLOAD_DOCKER_UID}:${IAUPLOAD_DOCKER_GID}"
    ports:
      - "${IAUPLOAD_PORT:-8080}:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/var/www/html
      - ./dev/000-default.conf:/etc/apache2/sites-available/000-default.conf:cached
      - ./dev/ports.conf:/etc/apache2/ports.conf:cached
      - ./dev/php.ini:/usr/local/etc/php/php.ini:cached
    environment:
      - APACHE_RUN_USER=daemon
      - XDEBUG_MODE=off

